spring:
  application:
    name: movie-api
    
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/movieapp
    
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          
  mail:
     host: smtp.gmail.com
     port: 587
     username: "praveenamaresh28@gmail.com"
     password: "vlqb lhqd erxa kgkk"
     properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      
          
          
project:
  poster: posters/
  
base:
  url: "http://localhost:8080/"
      
logging :
  file :
    name: app.log

# Size Based Rolling
  logback:
    rollingpolicy:
      file-name-pattern: ${app.log}.%d{yyyy-MM-dd}.%i.gz # by date
      max-file-size: 10MB # by size
#Time Based Rolling

      